/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GreenCardHashes } from "./GreenCardHashes";
export * as factories from "./factories";
export { GreenCardHashes__factory } from "./factories/GreenCardHashes__factory";
